### ISSUE TITLE
Compatibility with Nvim nightly (v0.5) ?

### ISSUE THREAD

**Issue by salkin-mada** [npxbr/glow.nvim#6] opened 2020-11-16 02:31 UTC
`:GlowInstall` does absolutely nothing on `NVIM v0.5.0-828-g0a95549d6`
Maybe i am missing something?

**Comment by ellisonleao** [comment] 2020-11-24 14:38
Hey @salkin-mada sorry for the late reply,  i will investigate this issue, but are you able to run the `:Glow` command already without any errors?

**Comment by salkin-mada** [comment] 2020-12-11 01:04
Hey. No stress i am also going a bit slow here as you can see :) haha.
I can NOT run the `:Glow` cmd - i get `zsh:1: command not found: glow [Process exited 127]`
because, yes. i don't have `glow`.  should running the `:GlowInstall` manually post/message something?
nothing to see in `:messages`.

**Comment by ellisonleao** [comment] 2020-12-11 01:44
hey @salkin-mada yeah i was able to reproduce on my side and i am already working in a fix. Thanks for the report

**Comment by salkin-mada** [comment] 2020-12-11 02:29
nice. let me know if i can help testing or something. cant wait to get my glow on and .md native preview/render going in nvim 0.5 
:)

**Comment by ellisonleao** [comment] 2020-12-11 03:04
@salkin-mada in the meantime you can install manually using `go get github.com/charmbracelet/glow` and just use the :Glow command

**Comment by ellisonleao** [comment] 2020-12-12 18:21
hey @salkin-mada just pushed a fix here, can you update and check if its working for you please? (note that GlowInstall can take some time to finish because go get -u for the glow project its taking some time to finish - at least on my side!)

**Comment by salkin-mada** [comment] 2020-12-14 10:59
tested here after update. and now I actually get some output when running `:GlowInstall`
but this is the result here.
![scrn-2020-12-14-11-59-47](https://user-images.githubusercontent.com/12082586/102073597-d1c36680-3e03-11eb-9b98-66ae69ae94ce.png)

**Comment by ellisonleao** [comment] 2020-12-14 12:56
@salkin-mada what is your go version?

**Comment by salkin-mada** [comment] 2020-12-14 13:02
`go version` go1.15.6 linux/amd64

**Comment by ellisonleao** [comment] 2020-12-14 13:15
weird, can you `go get -u github.com/charmbracelet/glow`  without errors?

**Comment by salkin-mada** [comment] 2020-12-14 13:25
i get
```
# github.com/charmbracelet/glamour/ansi
go/src/github.com/charmbracelet/glamour/ansi/renderer.go:76:15: undefined: "github.com/yuin/goldmark/extension/ast".KindFootnoteBackLink
```

**Comment by salkin-mada** [comment] 2020-12-14 13:29
same checking with `vet`
```
~
❯ go vet github.com/charmbracelet/glow
# github.com/charmbracelet/glamour/ansi
go/src/github.com/charmbracelet/glamour/ansi/renderer.go:76:15: undefined: "github.com/yuin/goldmark/extension/ast".KindFootnoteBackLink
```

**Comment by ellisonleao** [comment] 2020-12-14 13:42
weird, i have the same go version and i am not getting this. Seems like getting the compiled binary should be easiest path to solve that issue. Will think about something

**Comment by EMPAT94** [comment] 2021-02-19 03:41
+1 @ahmed-alahmadi @ellisonleao Same error on MacOS Catalina

---

:Glow -> glow is not installed. Call :GlowInstall to install it

:GlowInstall -> failed to install

$ go get -u github.com/charmbracelet/glow  -> cannot find package "github.com/hashicorp/hcl/hcl/printer" in any of:
	/usr/local/Cellar/go/1.15.8/libexec/src/github.com/hashicorp/hcl/hcl/printer (from $GOROOT)
	/Users/pritesh/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOPATH)

---

$  nvim --version
NVIM v0.5.0-dev+dc3ca16a9
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210216-17238-tw1nma/build/config -I/tmp/neovim-20210216-17238-tw1nma/src -I/usr/local/include -I/usr/local/opt/luv/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210216-17238-tw1nma/build/src/nvim/auto -I/tmp/neovim-20210216-17238-tw1nma/build/include
Compiled by pritesh@Priteshs-MacBook-Air.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-dc3ca16_1/share/nvim"

$  go version
go version go1.15.8 darwin/amd64

---

Hope it helps in debugging the issue. Let me know if you need a hand in testing. Cheers!

**Comment by ellisonleao** [comment] 2021-03-30 21:54
Closing this in favor of #8

**Closed by ellisonleao** 2021-03-30 21:54 UTC
Labels: bug
